bourakadb:
  image: postgres
  environment:
    - POSTGRES_PASSWORD=postgres
    - POSTGRES_DB=postgres
    - POSTGRES_USER=postgres
  volumes:
    - bouraka-db:/var/lib/postgresql/data
bourakaweb:
  build: .
  ports:
    - "12345:80"
  links:
    - bourakadb:db
  volumes:
    - bouraka-django:/bouraka/bouraka-django
    - bouraka-media:/bouraka/bouraka-media
    - bouraka-static:/bouraka/bouraka-static
